import type { STR as STRType } from './strings';

export const stringsEn: Partial<Record<keyof typeof STRType, string>> = {
  appName: 'Play Store',
  searchHint: 'Search apps',
  home: 'Home',
  myApps: 'My Apps',
  wishlist: 'Wishlist',
  categories: 'Categories',
  charts: 'Top Charts',
  settings: 'Settings',
  install: 'Install',
  installed: 'Installed',
  update: 'Update',
  uninstall: 'Uninstall',
  open: 'Open',
  cancel: 'Cancel',
  cancelDownload: 'Cancel Download',
  addToWishlist: 'Add to Wishlist',
  removeFromWishlist: 'Remove from Wishlist',
  writeReview: 'Write a Review',
  editReview: 'Edit Review',
  deleteReview: 'Delete Review',
  submitReview: 'Submit Review',
  rateApp: 'Rate',
  autoUpdate: 'Auto-update',
  globalUpdate: 'Global Auto-update Settings',
  developer: 'Developer',
  category: 'Category',
  size: 'Size',
  version: 'Version',
  rating: 'Rating',
  reviews: 'Reviews',
  downloads: 'Downloads',
  ageRating: 'Age Rating',
  updated: 'Updated',
  description: 'Description',
  whatIsNew: "What's New",
  allReviews: 'See All Reviews',
  noResults: 'No results found',
  noInstalled: 'No installed apps',
  noWishlist: 'Wishlist is empty',
  noDownloads: 'No download tasks',
  noUpdates: 'All apps are up to date',
  confirmUninstall: 'Confirm Uninstall',
  confirmUninstallMsg: 'Are you sure you want to uninstall this app?',
  downloadQueued: 'Queued',
  downloading: 'Downloading',
  downloadCompleted: 'Completed',
  downloadCancelled: 'Cancelled',
  queued: 'Queued',
  downloadingStatus: 'Downloading',
  completed: 'Completed',
  cancelled: 'Cancelled',
  installedTab: 'Installed',
  updatesTab: 'Updates',
  downloadsTab: 'Downloads',
  clearHistory: 'Clear History',
  searchHistory: 'Search History',
  sortBy: 'Sort by',
  relevance: 'Relevance',
  byRating: 'Rating',
  byDownloads: 'Downloads',
  bySize: 'Size',
  wifiOnly: 'Wi-Fi only',
  always: 'Always',
  never: 'Never',
};
