export const strings = {
  // ── Tabs ──
  tab_home: '首页',
  tab_send: '寄件',
  tab_me: '我的',
  // ── Home ──
  home_title: '我的包裹',
  home_search_placeholder: '搜运单号/快递单号',
  home_scan: '扫一扫',
  filter_all: '全部',
  filter_in_transit: '运输中',
  filter_arrived: '待取件',
  filter_picked: '已签收',
  home_empty: '暂无包裹',
  home_latest: '最新',
  home_eta_prefix: '预计',
  home_eta_suffix: '送达',
  home_pickup_code: '取件码',
  home_at_station: '已到驿站',
  // ── Search ──
  search_title: '查件',
  search_placeholder: '请输入快递单号',
  search_submit: '查询',
  search_no_result: '未查询到相关包裹',
  search_result: '查询结果',
  search_history: '搜索历史',
  search_clear: '清空',
  search_history_empty: '暂无搜索历史',
  search_open_detail: '查看详情',
  // ── Package detail ──
  detail_title: '物流详情',
  detail_tracking_no: '运单号',
  detail_carrier: '快递公司',
  detail_status: '当前状态',
  detail_eta: '预计送达',
  detail_route: '收发地址',
  detail_timeline: '物流跟踪',
  detail_station: '取件信息',
  detail_pickup_code: '取件码',
  detail_station_name: '驿站名称',
  detail_station_addr: '驿站地址',
  detail_station_hours: '营业时间',
  detail_confirm_pickup: '确认取件',
  detail_picked: '已取件',
  detail_from: '发件地',
  detail_to: '收件地',
  detail_weight: '重量',
  detail_item: '物品',
  detail_latest_node: '最新动态',
  detail_pickup_done_toast: '取件成功',
  // ── Send tab ──
  send_title: '寄件',
  send_create: '寄快递',
  send_records: '寄件记录',
  send_create_desc: '上门取件 · 经济实惠',
  send_records_desc: '查看历史寄件订单',
  // ── Send create ──
  sendc_title: '寄快递',
  sendc_sender_section: '寄件人',
  sendc_receiver_section: '收件人',
  sendc_name: '姓名',
  sendc_phone: '手机号',
  sendc_address: '地址',
  sendc_select_address: '从地址簿选择',
  sendc_item_section: '物品信息',
  sendc_item: '物品类型',
  sendc_weight: '重量(kg)',
  sendc_service_section: '服务与时间',
  sendc_service: '服务类型',
  sendc_carrier: '快递公司',
  sendc_pickup_time: '上门取件时间',
  sendc_note: '备注',
  sendc_fee: '预计费用',
  sendc_fee_suffix: '元',
  sendc_submit: '提交订单',
  sendc_required: '请填写完整寄件信息',
  sendc_success: '下单成功',
  // ── Send records ──
  records_title: '寄件记录',
  records_empty: '暂无寄件记录',
  records_fee_suffix: '元',
  records_pending: '待揽收',
  records_shipping: '运送中',
  records_completed: '已完成',
  records_created: '下单时间',
  // ── Send record detail ──
  srecord_title: '订单详情',
  srecord_status: '订单状态',
  srecord_fee: '订单费用',
  // ── Me ──
  me_title: '我的',
  me_edit_profile: '编辑资料',
  me_address_book: '地址簿',
  me_send_records: '我的寄件',
  me_notifications: '消息通知',
  me_settings: '设置',
  // ── Profile edit ──
  profile_title: '编辑资料',
  profile_nickname: '昵称',
  profile_name: '姓名',
  profile_phone: '手机号',
  profile_save: '保存',
  profile_saved: '已保存',
  // ── Address book ──
  addr_title: '地址簿',
  addr_add: '新增地址',
  addr_edit: '编辑地址',
  addr_default: '默认',
  addr_set_default: '设为默认',
  addr_delete: '删除',
  addr_name: '姓名',
  addr_phone: '手机号',
  addr_region: '所在地区',
  addr_detail: '详细地址',
  addr_tag: '标签',
  addr_save: '保存',
  addr_empty: '暂无地址',
  addr_select: '选择地址',
  addr_delete_confirm: '确认删除该地址？',
  // ── Notifications ──
  notif_title: '消息通知',
  notif_mark_read: '标记已读',
  notif_archive: '归档',
  notif_empty: '暂无消息',
  notif_unread: '未读',
  notif_archived: '已归档',
  // ── Notification detail ──
  ndetail_mark_read: '标记为已读',
  // ── Settings ──
  settings_title: '设置',
  settings_pickup_alert: '取件提醒',
  settings_transit_alert: '运输提醒',
  settings_arrival_alert: '到达提醒',
  settings_theme: '深色模式',
  settings_on: '开启',
  settings_off: '关闭',
  // ── Common ──
  common_cancel: '取消',
  common_confirm: '确认',
  common_save: '保存',
  common_back: '返回',
  common_not_available: '功能暂未开放',
} as const;

export type StringKey = keyof typeof strings;
