import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  tab_home: 'Home',
  tab_send: 'Send',
  tab_me: 'Me',
  home_title: 'My Parcels',
  home_search_placeholder: 'Search tracking number',
  home_scan: 'Scan',
  filter_all: 'All',
  filter_in_transit: 'In transit',
  filter_arrived: 'To pick up',
  filter_picked: 'Delivered',
  home_empty: 'No parcels',
  search_title: 'Track',
  search_placeholder: 'Enter tracking number',
  search_submit: 'Search',
  search_no_result: 'No matching parcel found',
  search_result: 'Result',
  search_history: 'History',
  search_clear: 'Clear',
  detail_title: 'Tracking detail',
  detail_confirm_pickup: 'Confirm pickup',
  send_title: 'Send',
  send_create: 'Send a parcel',
  send_records: 'Send records',
  me_title: 'Me',
  records_title: 'Send records',
  records_empty: 'No send records',
  addr_title: 'Address book',
  addr_add: 'Add address',
  addr_empty: 'No addresses',
  notif_title: 'Notifications',
  notif_empty: 'No messages',
  settings_title: 'Settings',
  common_cancel: 'Cancel',
  common_confirm: 'Confirm',
  common_save: 'Save',
  common_back: 'Back',
  common_not_available: 'Feature not available',
};
