import type { NavigationDeclaration, ScrollContainerDeclaration } from './navigation.types';

const MAIN_SCROLL: ScrollContainerDeclaration[] = [
  { name: 'main', direction: 'vertical', description: 'Main Content Area' },
];

export const NAVIGATION_DECLARATION: NavigationDeclaration = {
  app: 'baicizhan',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'home.base',
          search: {},
          description: '百词斩首页 - 今日学习概览',
          actions: [],
        },
      ],
      queryParams: {},
      description: '百词斩首页',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'me.base',
          search: {},
          description: '我的页面',
          actions: [],
        },
      ],
      queryParams: {},
      description: '我的页面',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'search.base',
          search: {},
          description: '搜索页面',
          actions: [
            { id: 'search.input.type', label: '输入搜索词', behavior: 'input', paramsSchema: { value: 'string' }, description: '在搜索框输入单词或释义' },
            { id: 'search.clear.tap', label: '清除搜索', behavior: 'other', description: '清除搜索内容' },
          ],
        },
      ],
      queryParams: { q: 'string' },
      description: '搜索单词页面',
    },
    {
      path: '/word/:wordId',
      component: 'WordDetailPage',
      params: { wordId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'word.base',
          search: {},
          description: '单词详情页',
          actions: [
            { id: 'word.favorite.toggle', label: '收藏/取消收藏', behavior: 'toggle', scope: 'item', paramsSchema: { wordId: 'string' }, description: '切换收藏状态' },
            { id: 'word.note.add', label: '添加笔记', behavior: 'other', description: '添加笔记' },
          ],
        },
      ],
      queryParams: {},
      description: '单词详情页',
    },
    {
      path: '/wordbooks',
      component: 'WordBooksPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'wordbooks.base',
          search: {},
          description: '词书列表页',
          actions: [],
        },
      ],
      queryParams: {},
      description: '词书列表页',
    },
    {
      path: '/wordbooks/:bookId',
      component: 'WordBookDetailPage',
      params: { bookId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'wordbookDetail.base',
          search: {},
          description: '词书详情页',
          actions: [],
        },
      ],
      queryParams: {},
      description: '词书详情页',
    },
    {
      path: '/study',
      component: 'StudySessionPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'study.base',
          search: {},
          description: '学习会话 - 单词卡',
          actions: [
            { id: 'study.word.known', label: '认识', behavior: 'other', scope: 'item', paramsSchema: { wordId: 'string' }, description: '标记为认识' },
            { id: 'study.word.unknown', label: '不认识', behavior: 'other', scope: 'item', paramsSchema: { wordId: 'string' }, description: '标记为不认识' },
            { id: 'study.word.showMeaning', label: '查看释义', behavior: 'other', description: '显示单词释义' },
            { id: 'study.complete.tap', label: '完成学习', behavior: 'other', description: '完成当前学习会话' },
          ],
        },
      ],
      queryParams: {},
      description: '每日学习页面',
    },
    {
      path: '/favorites',
      component: 'FavoritesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'favorites.base',
          search: {},
          description: '收藏夹页面',
          actions: [],
        },
      ],
      queryParams: {},
      description: '收藏夹页面',
    },
    {
      path: '/mistakes',
      component: 'MistakeBookPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'mistakes.base',
          search: {},
          description: '错题本页面',
          actions: [
            { id: 'mistakes.review.start', label: '开始复习', behavior: 'other', description: '开始错题复习' },
          ],
        },
      ],
      queryParams: {},
      description: '错题本页面',
    },
    {
      path: '/review-session',
      component: 'ReviewSessionPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'reviewSession.base',
          search: {},
          description: '复习会话页面',
          actions: [
            { id: 'reviewSession.word.showAnswer', label: '显示答案', behavior: 'other', description: '显示复习单词的释义' },
            { id: 'reviewSession.word.correct', label: '答对了', behavior: 'other', scope: 'item', paramsSchema: { wordId: 'string' }, description: '标记复习正确' },
            { id: 'reviewSession.word.incorrect', label: '答错了', behavior: 'other', scope: 'item', paramsSchema: { wordId: 'string' }, description: '标记复习错误' },
            { id: 'reviewSession.complete.tap', label: '完成复习', behavior: 'other', description: '完成复习会话' },
          ],
        },
      ],
      queryParams: {},
      description: '复习会话页面',
    },
    {
      path: '/spelling/:wordId',
      component: 'SpellingExercisePage',
      params: { wordId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'spelling.base',
          search: {},
          description: '拼写练习页面',
          actions: [
            { id: 'spelling.input.type', label: '输入拼写', behavior: 'input', paramsSchema: { value: 'string' }, description: '输入英文单词拼写' },
            { id: 'spelling.submit.tap', label: '提交拼写', behavior: 'submit', description: '提交拼写答案' },
          ],
        },
      ],
      queryParams: {},
      description: '拼写练习页面',
    },
    {
      path: '/listening/:wordId',
      component: 'ListeningExercisePage',
      params: { wordId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'listening.base',
          search: {},
          description: '听力练习页面 - 初始状态',
          actions: [
            { id: 'listening.play.tap', label: '播放发音', behavior: 'other', description: '点击播放单词发音' },
            { id: 'listening.select.option', label: '选择答案', behavior: 'select', scope: 'item', paramsSchema: { wordId: 'string' }, description: '选择听到的单词' },
            { id: 'listening.submit.tap', label: '提交答案', behavior: 'submit', description: '提交听力答案' },
          ],
        },
      ],
      queryParams: {},
      description: '听力练习页面',
    },
    {
      path: '/progress',
      component: 'DailyProgressPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'progress.base',
          search: {},
          description: '今日进度页面',
        },
      ],
      queryParams: {},
      description: '今日学习进度页面',
    },
    {
      path: '/statistics',
      component: 'StatisticsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'statistics.base',
          search: {},
          description: '学习统计页面',
        },
      ],
      queryParams: {},
      description: '学习统计页面',
    },
    {
      path: '/plan',
      component: 'StudyPlanPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'plan.base',
          search: {},
          description: '学习计划页面',
          actions: [
            { id: 'plan.select.goal', label: '设置每日目标', behavior: 'select', paramsSchema: { goal: 'number' }, description: '选择每日学习目标数量' },
            { id: 'plan.select.book', label: '切换词书', behavior: 'select', scope: 'item', paramsSchema: { bookId: 'string' }, description: '切换到指定词书' },
          ],
        },
      ],
      queryParams: {},
      description: '学习计划设置页面',
    },
    {
      path: '/settings',
      component: 'SettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.base',
          search: {},
          description: '设置页面',
          actions: [
            { id: 'settings.theme.toggle', label: '切换主题', behavior: 'toggle', description: '切换深色/浅色主题' },
          ],
        },
      ],
      queryParams: {},
      description: '设置页面',
    },
    {
      path: '/settings/reminder',
      component: 'ReminderPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'reminder.base',
          search: {},
          description: '学习提醒设置页面',
          actions: [
            { id: 'reminder.toggle.tap', label: '开关提醒', behavior: 'toggle', description: '开启或关闭学习提醒' },
            { id: 'reminder.select.time', label: '设置提醒时间', behavior: 'select', paramsSchema: { time: 'string' }, description: '选择提醒时间' },
          ],
        },
      ],
      queryParams: {},
      description: '学习提醒设置',
    },
  ],

  transitions: [
    // Tab switching
    {
      id: 'tab.home',
      from: ['/me', '/review-session', '/study'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到学习',
      ui: { placement: 'tabbar', icon: 'book', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: ['/'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我的',
      ui: { placement: 'tabbar', icon: 'user', gesture: 'tap' },
    },

    // Home page transitions
    {
      id: 'home.search.open',
      from: '/',
      to: '/search',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'home.study.start',
      from: '/',
      to: '/study',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '开始学习',
      ui: { placement: 'content', icon: 'play', gesture: 'tap' },
    },
    {
      id: 'home.review.start',
      from: ['/', '/mistakes'],
      to: '/review-session',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '开始复习',
      ui: { placement: 'content', icon: 'refresh', gesture: 'tap' },
    },
    {
      id: 'home.wordbooks.open',
      from: '/',
      to: '/wordbooks',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看词书',
      ui: { placement: 'content', icon: 'library', gesture: 'tap' },
    },
    {
      id: 'home.progress.open',
      from: '/',
      to: '/progress',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看今日进度',
      ui: { placement: 'content', icon: 'chart', gesture: 'tap' },
    },
    {
      id: 'home.mistakes.open',
      from: '/',
      to: '/mistakes',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看错题本',
      ui: { placement: 'content', icon: 'alert', gesture: 'tap' },
    },

    // Me page transitions
    {
      id: 'me.favorites.open',
      from: '/me',
      to: '/favorites',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开收藏夹',
      ui: { placement: 'content', icon: 'heart', gesture: 'tap' },
    },
    {
      id: 'me.mistakes.open',
      from: '/me',
      to: '/mistakes',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开错题本',
      ui: { placement: 'content', icon: 'alert', gesture: 'tap' },
    },
    {
      id: 'me.statistics.open',
      from: '/me',
      to: '/statistics',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开学习统计',
      ui: { placement: 'content', icon: 'chart', gesture: 'tap' },
    },
    {
      id: 'me.plan.open',
      from: '/me',
      to: '/plan',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开学习计划',
      ui: { placement: 'content', icon: 'settings', gesture: 'tap' },
    },
    {
      id: 'me.settings.open',
      from: '/me',
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开设置',
      ui: { placement: 'content', icon: 'settings', gesture: 'tap' },
    },

    // Search → Word Detail
    {
      id: 'search.word.open',
      from: '/search',
      to: '/word/:wordId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { wordId: 'string' },
      label: '打开单词详情',
      ui: { placement: 'content', icon: 'file', gesture: 'tap' },
    },

    // Word Detail → Exercises
    {
      id: 'word.spelling.open',
      from: '/word/:wordId',
      to: '/spelling/:wordId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { wordId: 'string' },
      label: '开始拼写练习',
      ui: { placement: 'content', icon: 'edit', gesture: 'tap' },
    },
    {
      id: 'word.listening.open',
      from: '/word/:wordId',
      to: '/listening/:wordId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { wordId: 'string' },
      label: '开始听力练习',
      ui: { placement: 'content', icon: 'volume', gesture: 'tap' },
    },

    // Favorites / Mistakes / WordBooks → Word Detail
    {
      id: 'favorites.word.open',
      from: '/favorites',
      to: '/word/:wordId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { wordId: 'string' },
      label: '打开单词详情',
      ui: { placement: 'content', icon: 'file', gesture: 'tap' },
    },
    {
      id: 'mistakes.word.open',
      from: '/mistakes',
      to: '/word/:wordId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { wordId: 'string' },
      label: '打开单词详情',
      ui: { placement: 'content', icon: 'file', gesture: 'tap' },
    },
    {
      id: 'wordbooks.word.open',
      from: '/wordbooks/:bookId',
      to: '/word/:wordId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { wordId: 'string' },
      label: '打开单词详情',
      ui: { placement: 'content', icon: 'file', gesture: 'tap' },
    },

    // Study Plan → Reminder
    {
      id: 'plan.reminder.open',
      from: '/plan',
      to: '/settings/reminder',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开学习提醒设置',
      ui: { placement: 'content', icon: 'bell', gesture: 'tap' },
    },
    {
      id: 'settings.reminder.open',
      from: '/settings',
      to: '/settings/reminder',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开学习提醒',
      ui: { placement: 'content', icon: 'bell', gesture: 'tap' },
    },

    // Word books detail
    {
      id: 'wordbooks.detail.open',
      from: '/wordbooks',
      to: '/wordbooks/:bookId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { bookId: 'string' },
      label: '打开词书详情',
      ui: { placement: 'content', icon: 'file', gesture: 'tap' },
    },
  ],

  capabilities: {
    historyBack: true,
  },
};
