const MAIN_SCROLL = [{ name: 'main', direction: 'vertical' as const, description: '页面主内容区' }];
const SHOP_SCROLL = [
  { name: 'main', direction: 'vertical' as const, description: '菜品列表区' },
  { name: 'category', direction: 'vertical' as const, description: '分类侧栏' },
];

export const NAVIGATION_DECLARATION = {
  app: 'meituan-lite',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'home.base', search: {}, description: '首页' }],
      queryParams: {},
      description: '首页：地址+搜索+分类宫格+横幅+附近商家',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'search.base', search: {}, description: '搜索页' }],
      queryParams: { q: 'string' },
      description: '搜索页：热词+商家过滤',
    },
    {
      path: '/shop/:shopId',
      component: 'ShopPage',
      params: { shopId: 'string' },
      entryPoint: 'none',
      scrollContainers: SHOP_SCROLL,
      uiStates: [
        { id: 'shop.base', search: {}, description: '商家详情/菜品列表' },
        { id: 'shop.cart', search: { cart: 'open' }, description: '购物车弹层展开' },
      ],
      queryParams: {},
      description: '商家详情：信息+公告+满减+分类侧栏+菜品+底部购物车栏',
    },
    {
      path: '/checkout',
      component: 'CheckoutPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'checkout.base', search: {}, description: '结算页' }],
      queryParams: {},
      description: '结算页：地址+配送时间+明细+优惠+备注+餐具+提交',
    },
    {
      path: '/payment/:orderId',
      component: 'PaymentPage',
      params: { orderId: 'string' },
      entryPoint: 'none',
      uiStates: [{ id: 'payment.base', search: {}, description: '支付确认页' }],
      queryParams: {},
      description: '模拟支付确认页',
    },
    {
      path: '/payment-success/:orderId',
      component: 'PaymentSuccessPage',
      params: { orderId: 'string' },
      entryPoint: 'none',
      uiStates: [{ id: 'paymentSuccess.base', search: {}, description: '支付成功页' }],
      queryParams: {},
      description: '支付成功页',
    },
    {
      path: '/orders',
      component: 'OrdersPage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'orders.base', search: {}, description: '订单列表页' }],
      queryParams: {},
      description: '订单 Tab：订单列表',
    },
    {
      path: '/order/:orderId',
      component: 'OrderDetailPage',
      params: { orderId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'orderDetail.base', search: {}, description: '订单详情页' }],
      queryParams: {},
      description: '订单详情页',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'me.base', search: {}, description: '我的页' }],
      queryParams: {},
      description: '我的 Tab：用户档案+入口',
    },
  ],
  transitions: [
    // ── 底部 Tab 切换（replace）──────────────────────────
    {
      id: 'tab.home',
      from: ['/', '/orders', '/me'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到首页',
      ui: { placement: 'tabbar', icon: 'home', gesture: 'tap' },
    },
    {
      id: 'tab.orders',
      from: ['/', '/orders', '/me'],
      to: '/orders',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到订单',
      ui: { placement: 'tabbar', icon: 'order', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: ['/', '/orders', '/me'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我的',
      ui: { placement: 'tabbar', icon: 'me', gesture: 'tap' },
    },

    // ── 搜索 ────────────────────────────────────────────
    {
      id: 'search.open',
      from: '/',
      to: '/search',
      search: {},
      searchParams: { q: 'string' },
      mode: 'push',
      params: {},
      label: '打开搜索',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },

    // ── 商家 ────────────────────────────────────────────
    {
      id: 'shop.open',
      from: ['/', '/search', '/order/:orderId'],
      to: '/shop/:shopId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开商家详情',
      ui: { placement: 'content', icon: 'arrow-right', gesture: 'tap' },
    },
    {
      id: 'shop.cart.open',
      from: '/shop/:shopId',
      to: '/shop/:shopId',
      search: { cart: 'open' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '展开购物车弹层',
      ui: { placement: 'content', icon: 'cart', gesture: 'tap' },
    },

    // ── 结算 / 支付 ─────────────────────────────────────
    {
      id: 'cart.checkout',
      from: '/shop/:shopId',
      to: '/checkout',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '去结算',
      ui: { placement: 'content', icon: 'cart', gesture: 'tap' },
    },
    {
      id: 'checkout.toPayment',
      from: '/checkout',
      to: '/payment/:orderId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '提交订单去支付',
      ui: { placement: 'content', icon: 'pay', gesture: 'tap' },
    },
    {
      id: 'payment.toSuccess',
      from: '/payment/:orderId',
      to: '/payment-success/:orderId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '确认支付',
      ui: { placement: 'content', icon: 'pay', gesture: 'tap' },
    },
    {
      id: 'paymentSuccess.viewOrder',
      from: '/payment-success/:orderId',
      to: '/order/:orderId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看订单',
      ui: { placement: 'content', icon: 'order', gesture: 'tap' },
    },
    {
      id: 'paymentSuccess.backHome',
      from: '/payment-success/:orderId',
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '返回首页',
      ui: { placement: 'content', icon: 'home', gesture: 'tap' },
    },

    // ── 订单 ────────────────────────────────────────────
    {
      id: 'orders.openOrder',
      from: '/orders',
      to: '/order/:orderId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看订单详情',
      ui: { placement: 'content', icon: 'arrow-right', gesture: 'tap' },
    },
  ],
  capabilities: { historyBack: true },
} as const;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
