import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  app_name: 'Meituan Lite',

  back: 'Back',
  cancel: 'Cancel',
  confirm: 'OK',
  submit: 'Submit',
  pay: 'Pay',
  yuan: '¥',
  free: 'Free',
  empty: 'No data',

  tab_home: 'Home',
  tab_orders: 'Orders',
  tab_me: 'Me',

  home_search_placeholder: 'Search shops, dishes',
  home_nearby: 'Nearby shops',
  home_banner_hongbao: 'Red packet rain up to ¥88',
  home_location_hint: 'Current location',

  cat_food: 'Food',
  cat_drink: 'Dessert & Drinks',
  cat_store: 'Grocery',
  cat_medicine: 'Pharmacy',
  cat_fruit: 'Fruit',
  cat_errand: 'Errands',
  cat_breakfast: 'Breakfast',
  cat_night: 'Late-night',

  shop_month_sales: 'sold/mo',
  shop_min_order: 'min',
  shop_delivery_fee: 'delivery',
  shop_delivery_time: 'min',
  shop_distance_km: 'km',
  shop_notice: 'Notice',
  shop_promotion: 'Promotion',
  shop_rating: 'Rating',
  shop_good_rate: 'good',
  shop_sold: 'sold',
  shop_add: 'Add',
  shop_category_hot: 'Hot',
  shop_back_to_home: 'Back home',

  cart_title: 'Cart',
  cart_empty: 'Cart is empty',
  cart_clear: 'Clear cart',
  cart_subtotal: 'Subtotal',
  cart_packing: 'Packing',
  cart_delivery: 'Delivery',
  cart_discount: 'Discount',
  cart_diff_to_min: '¥{0} more to min order',
  cart_go_checkout: 'Checkout',
  cart_item_count: 'items',

  checkout_title: 'Confirm Order',
  checkout_address: 'Delivery address',
  checkout_no_address: 'Select address',
  checkout_delivery_time: 'Delivery time',
  checkout_asap: 'ASAP',
  checkout_remark: 'Remark',
  checkout_remark_placeholder: 'Taste, preferences (optional)',
  checkout_utensils: 'Utensils',
  checkout_utensils_none: 'No utensils',
  checkout_utensils_n: '{0}',
  checkout_items: 'Items',
  checkout_payable: 'Total',
  checkout_submit: 'Submit order',
  checkout_contact: 'Contact',
  checkout_eta: 'ETA',

  pay_title: 'Confirm Payment',
  pay_amount: 'Amount',
  pay_method: 'Payment method',
  pay_method_balance: 'Balance',
  pay_method_bankcard: 'Bank card',
  pay_method_wechat: 'WeChat Pay',
  pay_method_alipay: 'Alipay',
  pay_balance: 'Balance',
  pay_simulated_notice: 'Simulated payment — no real charge',
  pay_confirm: 'Confirm Pay',
  pay_success: 'Paid',

  pay_success_title: 'Payment Successful',
  pay_success_order_no: 'Order no.',
  pay_success_eta: 'ETA',
  pay_success_status: 'Merchant accepted',
  pay_success_view_order: 'View order',
  pay_success_back_home: 'Back home',

  orders_title: 'My Orders',
  orders_empty: 'No orders yet',
  orders_status_pending: 'Pending payment',
  orders_status_accepted: 'Merchant accepted',
  orders_status_rider: 'Waiting for rider',
  orders_status_delivering: 'Delivering',
  orders_status_done: 'Completed',
  order_detail_title: 'Order Detail',
  order_status: 'Status',
  order_shop: 'Shop',
  order_items: 'Items',
  order_address: 'Address',
  order_pay_method: 'Payment',
  order_time: 'Order time',
  order_total: 'Total',
  order_again: 'Reorder',

  me_title: 'Me',
  me_orders: 'My orders',
  me_wallet: 'Wallet',
  me_balance: 'Balance',
  me_address: 'Addresses',
  me_service: 'Support',
  me_settings: 'Settings',
  me_simulated_user: 'Simulated user',
};
