import { createAppStoreWithActions } from '../../os/createAppStore'; import { now } from '../../os/TimeService'; import { GMAIL_CONFIG } from './data'; import type { ComposeInput,GmailActions,GmailMessage,GmailState,GmailThread,GmailDraft,GmailLabel } from './types';
const initialState:GmailState={ user:{...GMAIL_CONFIG.user}, threads:structuredClone(GMAIL_CONFIG.threads) as Record<string,GmailThread>, messages:structuredClone(GMAIL_CONFIG.messages) as Record<string,GmailMessage>, drafts:{}, sent:{}, labels:structuredClone(GMAIL_CONFIG.labels) as Record<string,GmailLabel>, search:{query:'',resultThreadIds:[]}, _temp:{lastSearchQuery:null,lastOpenedThreadId:null,lastOpenedMessageId:null,searchHistory:[],openedThreadIds:[]} };
const addresses=(v:string)=>v.split(/[,;\n]/).map(x=>x.trim()).filter(Boolean);
export const parseAddresses=addresses;
export const useGmailStore=createAppStoreWithActions<GmailState,GmailActions>('gmail',initialState,(set,get)=>({
 searchThreads:(query)=>{const q=query.trim().toLowerCase();const s=get();const ids=Object.values(s.threads).filter(t=>t.messageIds.some(id=>{const m=s.messages[id]??s.sent[id];return m&&[m.from,m.to.join(' '),m.subject,m.body,...m.attachments.map(a=>a.name)].join(' ').toLowerCase().includes(q)})).map(t=>t.id);set(x=>({search:{query,resultThreadIds:ids},_temp:{...x._temp,lastSearchQuery:query,searchHistory:[query,...x._temp.searchHistory.filter(v=>v!==query)].slice(0,20)}}))},
 openThread:(threadId)=>set(s=>{const t=s.threads[threadId];return {threads:t?{...s.threads,[threadId]:{...t,isRead:true}}:s.threads,_temp:{...s._temp,lastOpenedThreadId:threadId,lastOpenedMessageId:t?.messageIds.at(-1)??null,openedThreadIds:[threadId,...s._temp.openedThreadIds.filter(x=>x!==threadId)]}}}),
 toggleStar:(id)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],isStarred:!s.threads[id].isStarred}}})), toggleImportant:(id)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],isImportant:!s.threads[id].isImportant}}})), markUnread:(id)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],isRead:false}}})),
 archiveThread:(id)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],folder:'archive'}}})), trashThread:(id)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],folder:'trash'}}})), restoreThread:(id)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],folder:'inbox'}}})), spamThread:(id)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],folder:'spam'}}})),
 applyLabel:(id,l)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],labelIds:Array.from(new Set([...s.threads[id].labelIds,l]))}}})), removeLabel:(id,l)=>set(s=>({threads:{...s.threads,[id]:{...s.threads[id],labelIds:s.threads[id].labelIds.filter(x=>x!==l)}}})),
 createLabel:(name,threadId)=>{const id=`label_${now()}`;set(s=>({labels:{...s.labels,[id]:{id,name:name.trim(),color:'#a142f4'}},threads:threadId?{...s.threads,[threadId]:{...s.threads[threadId],labelIds:[...s.threads[threadId].labelIds,id]}}:s.threads}));return id},
 saveDraft:(input)=>{const id=`draft_${now()}`;const d:GmailDraft={id,to:input.to,cc:input.cc,bcc:input.bcc,subject:input.subject,body:input.body,attachments:[],replyToThreadId:input.replyToThreadId??null,forwardOfMessageId:input.forwardOfMessageId??null,updatedAt:now()};set(s=>({drafts:{...s.drafts,[id]:d}}));return id},
 sendMessage:(input)=>{const ts=now(),id=`sent_${ts}`,threadId=input.replyToThreadId??`thread_sent_${ts}`;const m:GmailMessage={id,threadId,from:get().user.email,to:input.to,cc:input.cc,bcc:input.bcc,subject:input.subject,body:input.body,attachments:[],sentAt:ts};set(s=>{const old=s.threads[threadId];return {sent:{...s.sent,[id]:m},messages:{...s.messages,[id]:m},threads:{...s.threads,[threadId]:old?{...old,messageIds:[...old.messageIds,id],folder:'archive',updatedAt:ts}:{id:threadId,messageIds:[id],folder:'archive',isRead:true,isStarred:false,isImportant:false,labelIds:[],updatedAt:ts}}}});return id},
 permanentlyDelete:(id)=>set(s=>{const {[id]:removed,...threads}=s.threads;const messages={...s.messages};removed?.messageIds.forEach(mid=>delete messages[mid]);return {threads,messages}})
}));
