export const stringsEn = {
  tab_home: 'Home',
  tab_mall: 'Mall',
  tab_me: 'Me',
  home_title: 'China Mobile',
  home_subtitle: 'Balance',
  home_data: 'Data',
  home_voice: 'Voice',
  home_plan: 'Plan',
  home_points: 'Points',
  home_yuan: 'CNY',
  home_gb: 'GB',
  home_min: 'min',
  home_recharge_btn: 'Recharge',
  balance_title: 'Balance',
  data_title: 'Data Usage',
  voice_title: 'Voice Usage',
  plan_title: 'Plan',
  planchange_title: 'Change Plan',
  bill_title: 'Bills',
  bill_detail_title: 'Bill Detail',
  recharge_title: 'Recharge',
  services_title: 'Subscribed Services',
  roaming_title: 'International Roaming',
  autopay_title: 'Auto Pay',
  family_title: 'Family Numbers',
  search_title: 'Service Search',
  profile_title: 'Profile',
  email_title: 'Edit Email',
  orders_title: 'Transactions',
  settings_title: 'Settings',
  common_cancel: 'Cancel',
  common_confirm: 'Confirm',
  common_save: 'Save',
  common_back: 'Back',
  common_yuan: 'CNY',
} as const;
