export const strings = {
  // ── Tabs ──
  tab_home: '首页',
  tab_mall: '商城',
  tab_me: '我的',
  // ── Home ──
  home_title: '中国移动',
  home_subtitle: '话费余额',
  home_data: '剩余流量',
  home_voice: '剩余语音',
  home_plan: '当前套餐',
  home_points: '我的积分',
  home_quick_recharge: '充值',
  home_quick_datapack: '流量包',
  home_quick_bill: '账单',
  home_quick_plan: '套餐',
  home_quick_balance: '余额',
  home_quick_services: '已订业务',
  home_quick_family: '亲情号',
  home_quick_more: '更多',
  home_search_placeholder: '搜索服务',
  home_yuan: '元',
  home_gb: 'GB',
  home_min: '分钟',
  home_recharge_btn: '充值',
  // ── Balance ──
  balance_title: '话费余额',
  balance_current: '当前余额',
  balance_payable: '本月已出账',
  balance_arrears: '欠费金额',
  balance_arrears_hint: '您有欠费账单，请尽快缴纳',
  balance_recharge: '立即充值',
  balance_recent: '近期交易',
  // ── Data ──
  data_title: '流量用量',
  data_remaining_highspeed: '本月剩余高速流量',
  data_total: '套餐内总量',
  data_used: '已使用',
  data_purchased: '已购加油包',
  data_buy: '购买流量包',
  // ── Voice ──
  voice_title: '语音用量',
  voice_remaining: '本月剩余语音分钟',
  voice_total: '套餐内分钟',
  voice_used: '已使用',
  // ── Plan ──
  plan_title: '套餐详情',
  plan_current: '当前套餐',
  plan_price: '月费',
  plan_data: '套餐流量',
  plan_voice: '套餐语音',
  plan_change: '变更套餐',
  // ── Plan change ──
  planchange_title: '变更套餐',
  planchange_select: '选择',
  planchange_selected: '已选',
  planchange_confirm: '确认变更',
  planchange_confirm_title: '确认套餐变更',
  planchange_current: '当前套餐',
  planchange_to: '变更为',
  planchange_hint: '新套餐下月生效',
  // ── Bill ──
  bill_title: '月度账单',
  bill_month: '账期',
  bill_total: '账单总额',
  bill_status_current: '本月未出账',
  bill_status_unpaid: '未缴欠费',
  bill_status_paid: '已缴清',
  bill_view_detail: '查看明细',
  bill_pay: '立即缴费',
  bill_detail_title: '账单明细',
  bill_category: '费用分类',
  bill_amount: '金额',
  // ── Recharge ──
  recharge_title: '话费充值',
  recharge_amount: '充值金额',
  recharge_method: '支付方式',
  recharge_confirm: '立即充值',
  recharge_confirm_title: '确认充值',
  recharge_success: '充值成功',
  recharge_balance_after: '充值后余额',
  // ── Services ──
  services_title: '已订业务',
  services_vas: '增值业务',
  services_price: '月费',
  services_free: '免费',
  services_on: '已开通',
  services_off: '未开通',
  services_uncancellable: '不可退订',
  services_cancel: '退订',
  services_subscribe: '开通',
  // ── Roaming ──
  roaming_title: '国际漫游',
  roaming_desc: '出境时使用国际数据与语音服务',
  roaming_on: '已开通',
  roaming_off: '未开通',
  // ── Autopay ──
  autopay_title: '自动缴费',
  autopay_enable: '开启自动缴费',
  autopay_method: '缴费方式',
  autopay_save: '保存设置',
  autopay_on: '已开启',
  autopay_off: '未开启',
  autopay_saved: '已保存',
  // ── Family ──
  family_title: '亲情号码',
  family_add: '添加',
  family_phone: '手机号',
  family_nickname: '昵称',
  family_save: '保存',
  family_delete: '删除',
  family_empty: '暂无亲情号码',
  family_add_title: '添加亲情号码',
  family_delete_confirm: '确认删除该亲情号码？',
  // ── Search ──
  search_title: '服务搜索',
  search_placeholder: '输入服务名称',
  search_submit: '搜索',
  search_clear: '清空',
  search_empty: '暂无相关服务',
  search_history: '搜索历史',
  // ── Profile ──
  profile_title: '个人资料',
  profile_name: '姓名',
  profile_phone: '手机号',
  profile_email: '联系邮箱',
  profile_idno: '证件号',
  profile_address: '通讯地址',
  profile_edit_email: '修改邮箱',
  // ── Email edit ──
  email_title: '修改联系邮箱',
  email_label: '联系邮箱',
  email_save: '保存',
  email_invalid: '请输入有效的邮箱地址',
  email_saved: '邮箱已更新',
  // ── Orders ──
  orders_title: '交易记录',
  orders_empty: '暂无交易记录',
  orders_type_recharge: '充值',
  orders_type_payment: '缴费',
  orders_type_datapack: '购流量包',
  orders_type_planchange: '套餐变更',
  orders_type_service: '业务办理',
  // ── Settings ──
  settings_title: '设置',
  settings_data_alert: '流量预警',
  settings_marketing: '营销推送',
  settings_theme: '深色模式',
  settings_on: '开启',
  settings_off: '关闭',
  // ── Common ──
  common_cancel: '取消',
  common_confirm: '确认',
  common_save: '保存',
  common_back: '返回',
  common_yuan: '元',
  common_not_available: '功能暂未开放',
  common_fail_balance: '余额不足',
} as const;

export type StringKey = keyof typeof strings;
