import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  appName: 'Wallet',
  home: 'Wallet',
  coupons: 'Offers',
  me: 'Me',
  search: 'Search',
  addCard: 'Add Card',
  addBankCard: 'Add Bank Card',
  addTransitCard: 'Add Transit Card',
  addMembershipCard: 'Add Membership Card',
  addCoupon: 'Add Coupon',
  bankCards: 'Bank Cards',
  transitCards: 'Transit Cards',
  membershipCards: 'Membership',
  couponsTitle: 'Coupons',
  ticketsTitle: 'Tickets',
  archived: 'Archived',
  defaultCard: 'Default',
  setDefault: 'Set as Default',
  rename: 'Rename',
  freeze: 'Freeze',
  unfreeze: 'Unfreeze',
  delete: 'Delete',
  confirmDelete: 'Confirm Delete',
  deleteConfirmMessage: 'This card will be removed. Continue?',
  cancel: 'Cancel',
  confirm: 'Confirm',
  save: 'Save',
  cardName: 'Card Name',
  bankName: 'Bank',
  cardHolder: 'Card Holder',
  last4: 'Last 4 Digits',
  cardNumber: 'Card Number',
  memberNumber: 'Member Number',
  city: 'City',
  merchant: 'Merchant',
  couponCode: 'Coupon Code',
  value: 'Value',
  expiry: 'Valid Until',
  points: 'Points',
  balance: 'Balance',
  recharge: 'Recharge',
  rechargeAmount: 'Recharge Amount',
  redeem: 'Redeem',
  reward: 'Reward',
  redeemReward: 'Redeem Reward',
  archive: 'Archive',
  showCode: 'Show Code',
  noResults: 'No results',
  emptyState: 'No cards yet',
  settings: 'Settings',
  theme: 'Theme',
  notifications: 'Notifications',
  sort: 'Sort',
  filterAll: 'All',
  back: 'Back',
  cardDetail: 'Card Detail',
  code: 'Payment Code',
  barcode: 'Barcode',
  qrcode: 'QR Code',
};
