// apps/Telegram/res/strings.ts
// Telegram App 字符串资源

export const STR = {
  app: {
    name: 'Telegram',
  },
  tabs: {
    chats: 'Chats',
    contacts: 'Contacts',
    settings: 'Settings',
  },
  chat: {
    title: 'Chat',
    input: 'Message',
    send: 'Send',
    reply: 'Reply',
    edit: 'Edit',
    delete: 'Delete',
    forward: 'Forward',
    pin: 'Pin Message',
    unpin: 'Unpin',
    reactions: 'Reactions',
    edited: 'edited',
    forwardedFrom: 'Forwarded from',
    search: 'Search',
    noMessages: 'No messages yet',
    tapToStart: 'Tap to start conversation',
    longPressHint: 'Long press a message for options',
    confirmDelete: 'Delete this message?',
    confirmDeleteGroup: 'Delete these messages?',
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
  },
  chatList: {
    title: 'Chats',
    search: 'Search',
    noChats: 'No chats yet',
    archived: 'Archived Chats',
    pinned: 'Pinned',
    muted: 'Muted',
    unread: 'Unread',
    markAsRead: 'Mark as Read',
    markAsUnread: 'Mark as Unread',
    pinChat: 'Pin',
    unpinChat: 'Unpin',
    mute: 'Mute',
    unmute: 'Unmute',
    archive: 'Archive',
    unarchive: 'Unarchive',
    delete: 'Delete',
  },
  contacts: {
    title: 'Contacts',
    search: 'Search contacts',
    noContacts: 'No contacts found',
    online: 'online',
    lastSeen: 'last seen',
    invite: 'Invite Friends',
  },
  group: {
    create: 'New Group',
    name: 'Group Name',
    members: 'Members',
    addMembers: 'Add Members',
    selectMembers: 'Select at least 2 members',
    enterName: 'Enter group name',
    createButton: 'Create Group',
    editName: 'Edit Group Name',
    newName: 'New group name',
    save: 'Save',
    cancel: 'Cancel',
  },
  settings: {
    title: 'Settings',
    notifications: 'Notifications',
    privacy: 'Privacy',
    appearance: 'Appearance',
    data: 'Data and Storage',
    help: 'Help',
    about: 'About',
    editProfile: 'Edit Profile',
  },
  common: {
    back: 'Back',
    done: 'Done',
    save: 'Save',
    cancel: 'Cancel',
    ok: 'OK',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    more: 'More',
  },
};
