export const strings = {
  // Tabs
  tab_home: '首页',
  tab_category: '分类',
  tab_cart: '购物车',
  tab_me: '我的淘宝',

  // Home
  home_search_placeholder: '搜索商品、品牌、店铺',
  home_recommend: '猜你喜欢',
  home_categories: '分类入口',
  home_recently_viewed: '最近浏览',

  // Search
  search_title: '搜索',
  search_placeholder: '搜索商品',
  search_history: '搜索历史',
  search_clear: '清除历史',
  search_hot: '热门搜索',
  search_no_results: '未找到相关商品',
  search_results_count: '共{count}个结果',
  search_sort_comprehensive: '综合',
  search_sort_sales: '销量',
  search_sort_price_asc: '价格升序',
  search_sort_price_desc: '价格降序',
  search_sort_rating: '评分',
  search_filter: '筛选',
  search_filter_category: '分类',
  search_filter_brand: '品牌',
  search_filter_price: '价格区间',
  search_filter_free_shipping: '包邮',
  search_filter_rating: '评分',
  search_filter_reset: '重置',
  search_filter_apply: '确定',
  search_cancel: '取消',

  // Product Detail
  product_title: '商品详情',
  product_price: '价格',
  product_original_price: '原价',
  product_sales: '已售',
  product_rating: '评分',
  product_reviews: '评价',
  product_sku_select: '请选择规格',
  product_quantity: '数量',
  product_stock: '库存',
  product_add_to_cart: '加入购物车',
  product_buy_now: '立即购买',
  product_favorite: '收藏',
  product_favorited: '已收藏',
  product_enter_shop: '进入店铺',
  product_free_shipping: '包邮',
  product_shipping_fee: '运费',
  product_description: '商品描述',
  product_shop: '店铺',
  product_brand: '品牌',
  product_category: '分类',

  // Cart
  cart_title: '购物车',
  cart_empty: '购物车是空的',
  cart_go_shopping: '去逛逛',
  cart_select_all: '全选',
  cart_total: '合计',
  cart_checkout: '结算',
  cart_checkout_count: '结算({count})',
  cart_delete: '删除',
  cart_delete_confirm: '确定要删除该商品吗？',
  cart_delete_confirm_yes: '删除',
  cart_delete_confirm_no: '取消',
  cart_edit: '编辑',

  // Coupons
  coupon_title: '优惠券',
  coupon_platform: '平台券',
  coupon_shop: '店铺券',
  coupon_claim: '领取',
  coupon_claimed: '已领取',
  coupon_used: '已使用',
  coupon_threshold: '满{amount}减{discount}',
  coupon_no_available: '暂无可用优惠券',
  coupon_select: '选择优惠券',
  coupon_use: '使用',

  // Address
  address_title: '收货地址',
  address_add: '新增地址',
  address_edit: '编辑地址',
  address_delete: '删除',
  address_delete_confirm: '确定要删除该地址吗？',
  address_default: '默认',
  address_set_default: '设为默认',
  address_name: '收货人',
  address_phone: '手机号',
  address_province: '省',
  address_city: '市',
  address_district: '区',
  address_detail: '详细地址',
  address_save: '保存',
  address_select: '选择地址',
  address_required: '请填写完整地址信息',

  // Checkout
  checkout_title: '确认订单',
  checkout_items: '商品信息',
  checkout_address: '收货地址',
  checkout_coupon: '优惠券',
  checkout_shipping: '配送方式',
  checkout_shipping_standard: '标准配送',
  checkout_shipping_express: '快递配送',
  checkout_subtotal: '商品小计',
  checkout_shipping_fee: '运费',
  checkout_discount: '优惠',
  checkout_payable: '应付',
  checkout_submit: '提交订单',
  checkout_address_required: '请选择收货地址',
  checkout_empty: '请选择要结算的商品',

  // Payment
  payment_title: '支付',
  payment_amount: '支付金额',
  payment_method: '支付方式',
  payment_simulate: '模拟支付',
  payment_success: '支付成功',
  payment_cancel: '取消支付',

  // Orders
  order_title: '我的订单',
  order_all: '全部',
  order_pending_payment: '待付款',
  order_to_ship: '待发货',
  order_shipped: '待收货',
  order_received: '已完成',
  order_cancelled: '已取消',
  order_detail: '订单详情',
  order_id: '订单号',
  order_status: '订单状态',
  order_items: '商品信息',
  order_subtotal: '小计',
  order_discount: '优惠',
  order_shipping: '运费',
  order_payable: '实付',
  order_cancel: '取消订单',
  order_cancel_confirm: '确定要取消该订单吗？',
  order_pay: '去支付',
  order_confirm_receipt: '确认收货',
  order_confirm_receipt_confirm: '确定已收到商品吗？',
  order_track: '查看物流',
  order_refund: '申请退款',
  order_review: '评价',

  // Logistics
  logistics_title: '物流详情',
  logistics_carrier: '承运公司',
  logistics_tracking_no: '运单号',
  logistics_status: '物流状态',
  logistics_in_transit: '运输中',
  logistics_out_for_delivery: '派送中',
  logistics_delivered: '已签收',
  logistics_estimated: '预计送达',
  logistics_latest: '最新动态',

  // Refund
  refund_title: '申请退款',
  refund_reason: '退款原因',
  refund_reason_placeholder: '请选择退款原因',
  refund_note: '退款说明',
  refund_note_placeholder: '请填写退款说明（选填）',
  refund_submit: '提交退款申请',
  refund_status_pending: '待处理',
  refund_status_approved: '已同意',
  refund_status_refunded: '已退款',
  refund_status_rejected: '已拒绝',
  refund_duplicate: '该商品已申请过退款',

  // Review
  review_title: '评价',
  review_rating: '评分',
  review_content: '评价内容',
  review_content_placeholder: '分享你的使用体验吧',
  review_tags: '标签',
  review_submit: '提交评价',
  review_success: '评价成功',

  // Favorites
  fav_title: '我的收藏',
  fav_empty: '还没有收藏商品',
  fav_remove: '取消收藏',

  // Me / Profile
  me_title: '我的淘宝',
  me_orders: '我的订单',
  me_favorites: '我的收藏',
  me_coupons: '优惠券',
  me_addresses: '收货地址',
  me_settings: '设置',
  me_recently_viewed: '最近浏览',
  me_view_all_orders: '查看全部订单',

  // Settings
  settings_title: '设置',
  settings_theme: '主题',
  settings_theme_light: '浅色',
  settings_theme_dark: '深色',
  settings_notification: '消息通知',
  settings_about: '关于',

  // Shop
  shop_title: '店铺',
  shop_products: '全部商品',
  shop_rating: '店铺评分',
  shop_search: '搜索店内商品',
  shop_all_products: '全部商品',

  // Common
  common_confirm: '确定',
  common_cancel: '取消',
  common_save: '保存',
  common_delete: '删除',
  common_back: '返回',
  common_close: '关闭',
  common_more: '更多',
  common_loading: '加载中...',
  common_disabled: '暂未开放',
} as const;

export type StringKey = keyof typeof strings;
