import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  tab_home: 'Home',
  tab_category: 'Categories',
  tab_cart: 'Cart',
  tab_me: 'Me',

  home_search_placeholder: 'Search products, brands, shops',
  home_recommend: 'Recommended',
  home_categories: 'Categories',
  home_recently_viewed: 'Recently Viewed',

  search_title: 'Search',
  search_placeholder: 'Search products',
  search_history: 'Search History',
  search_clear: 'Clear History',
  search_hot: 'Hot Searches',
  search_no_results: 'No results found',
  search_results_count: '{count} results',
  search_sort_comprehensive: 'Best Match',
  search_sort_sales: 'Sales',
  search_sort_price_asc: 'Price Low to High',
  search_sort_price_desc: 'Price High to Low',
  search_sort_rating: 'Rating',
  search_filter: 'Filter',
  search_filter_category: 'Category',
  search_filter_brand: 'Brand',
  search_filter_price: 'Price Range',
  search_filter_free_shipping: 'Free Shipping',
  search_filter_rating: 'Rating',
  search_filter_reset: 'Reset',
  search_filter_apply: 'Apply',
  search_cancel: 'Cancel',

  product_title: 'Product Details',
  product_price: 'Price',
  product_original_price: 'Original',
  product_sales: 'Sold',
  product_rating: 'Rating',
  product_reviews: 'Reviews',
  product_sku_select: 'Select options',
  product_quantity: 'Quantity',
  product_stock: 'In Stock',
  product_add_to_cart: 'Add to Cart',
  product_buy_now: 'Buy Now',
  product_favorite: 'Favorite',
  product_favorited: 'Favorited',
  product_enter_shop: 'Enter Shop',
  product_free_shipping: 'Free Shipping',
  product_shipping_fee: 'Shipping Fee',
  product_description: 'Description',
  product_shop: 'Shop',
  product_brand: 'Brand',
  product_category: 'Category',

  cart_title: 'Shopping Cart',
  cart_empty: 'Your cart is empty',
  cart_go_shopping: 'Go Shopping',
  cart_select_all: 'Select All',
  cart_total: 'Total',
  cart_checkout: 'Checkout',
  cart_checkout_count: 'Checkout({count})',
  cart_delete: 'Delete',
  cart_delete_confirm: 'Remove this item?',
  cart_delete_confirm_yes: 'Remove',
  cart_delete_confirm_no: 'Cancel',
  cart_edit: 'Edit',

  coupon_title: 'Coupons',
  coupon_platform: 'Platform',
  coupon_shop: 'Shop',
  coupon_claim: 'Claim',
  coupon_claimed: 'Claimed',
  coupon_used: 'Used',
  coupon_threshold: 'Spend {amount}, save {discount}',
  coupon_no_available: 'No coupons available',
  coupon_select: 'Select Coupon',
  coupon_use: 'Use',

  address_title: 'Addresses',
  address_add: 'Add Address',
  address_edit: 'Edit Address',
  address_delete: 'Delete',
  address_delete_confirm: 'Delete this address?',
  address_default: 'Default',
  address_set_default: 'Set Default',
  address_name: 'Recipient',
  address_phone: 'Phone',
  address_province: 'Province',
  address_city: 'City',
  address_district: 'District',
  address_detail: 'Detail Address',
  address_save: 'Save',
  address_select: 'Select Address',
  address_required: 'Please fill in complete address',

  checkout_title: 'Checkout',
  checkout_items: 'Items',
  checkout_address: 'Shipping Address',
  checkout_coupon: 'Coupon',
  checkout_shipping: 'Shipping Method',
  checkout_shipping_standard: 'Standard Shipping',
  checkout_shipping_express: 'Express Shipping',
  checkout_subtotal: 'Subtotal',
  checkout_shipping_fee: 'Shipping',
  checkout_discount: 'Discount',
  checkout_payable: 'Payable',
  checkout_submit: 'Submit Order',
  checkout_address_required: 'Please select a shipping address',
  checkout_empty: 'Please select items to checkout',

  payment_title: 'Payment',
  payment_amount: 'Amount',
  payment_method: 'Payment Method',
  payment_simulate: 'Simulate Payment',
  payment_success: 'Payment Successful',
  payment_cancel: 'Cancel Payment',

  order_title: 'My Orders',
  order_all: 'All',
  order_pending_payment: 'To Pay',
  order_to_ship: 'To Ship',
  order_shipped: 'Shipping',
  order_received: 'Completed',
  order_cancelled: 'Cancelled',
  order_detail: 'Order Details',
  order_id: 'Order ID',
  order_status: 'Status',
  order_items: 'Items',
  order_subtotal: 'Subtotal',
  order_discount: 'Discount',
  order_shipping: 'Shipping',
  order_payable: 'Total',
  order_cancel: 'Cancel Order',
  order_cancel_confirm: 'Cancel this order?',
  order_pay: 'Pay Now',
  order_confirm_receipt: 'Confirm Receipt',
  order_confirm_receipt_confirm: 'Confirm you received the items?',
  order_track: 'Track',
  order_refund: 'Request Refund',
  order_review: 'Review',

  logistics_title: 'Logistics',
  logistics_carrier: 'Carrier',
  logistics_tracking_no: 'Tracking No.',
  logistics_status: 'Status',
  logistics_in_transit: 'In Transit',
  logistics_out_for_delivery: 'Out for Delivery',
  logistics_delivered: 'Delivered',
  logistics_estimated: 'Estimated Delivery',
  logistics_latest: 'Latest Update',

  refund_title: 'Request Refund',
  refund_reason: 'Reason',
  refund_reason_placeholder: 'Select refund reason',
  refund_note: 'Note',
  refund_note_placeholder: 'Add a note (optional)',
  refund_submit: 'Submit Refund Request',
  refund_status_pending: 'Pending',
  refund_status_approved: 'Approved',
  refund_status_refunded: 'Refunded',
  refund_status_rejected: 'Rejected',
  refund_duplicate: 'A refund has already been requested',

  review_title: 'Review',
  review_rating: 'Rating',
  review_content: 'Review',
  review_content_placeholder: 'Share your experience',
  review_tags: 'Tags',
  review_submit: 'Submit Review',
  review_success: 'Review submitted',

  fav_title: 'My Favorites',
  fav_empty: 'No favorites yet',
  fav_remove: 'Remove',

  me_title: 'My Taobao',
  me_orders: 'My Orders',
  me_favorites: 'Favorites',
  me_coupons: 'Coupons',
  me_addresses: 'Addresses',
  me_settings: 'Settings',
  me_recently_viewed: 'Recently Viewed',
  me_view_all_orders: 'View All Orders',

  settings_title: 'Settings',
  settings_theme: 'Theme',
  settings_theme_light: 'Light',
  settings_theme_dark: 'Dark',
  settings_notification: 'Notifications',
  settings_about: 'About',

  shop_title: 'Shop',
  shop_products: 'All Products',
  shop_rating: 'Shop Rating',
  shop_search: 'Search in shop',
  shop_all_products: 'All Products',

  common_confirm: 'Confirm',
  common_cancel: 'Cancel',
  common_save: 'Save',
  common_delete: 'Delete',
  common_back: 'Back',
  common_close: 'Close',
  common_more: 'More',
  common_loading: 'Loading...',
  common_disabled: 'Not Available',
} as const;
