const MAIN_SCROLL = [{ name: 'main', direction: 'vertical' as const, description: '页面主内容区' }];
const NO_SCROLL: { name: string; direction: 'vertical'; description: string }[] = [];

export const NAVIGATION_DECLARATION = {
  app: 'wallet',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'wallet.home.base',
          search: {},
          description: '钱包首页',
        },
      ],
      queryParams: { filter: 'string', search: 'string' },
      description: '钱包首页',
    },
    {
      path: '/card/:id',
      component: 'CardDetailPage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'wallet.cardDetail.base',
          search: {},
          description: '卡片详情',
        },
      ],
      queryParams: { dialog: 'string' },
      description: '卡片详情',
    },
    {
      path: '/card/:id/code',
      component: 'CodePage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: NO_SCROLL,
      uiStates: [{ id: 'wallet.cardCode.base', search: {}, description: '付款码展示' }],
      queryParams: {},
      description: '付款码展示',
    },
    {
      path: '/add/bank',
      component: 'AddBankCardPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.addBank.base', search: {}, description: '添加银行卡' }],
      queryParams: {},
      description: '添加银行卡',
    },
    {
      path: '/add/transit',
      component: 'AddTransitCardPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.addTransit.base', search: {}, description: '添加交通卡' }],
      queryParams: {},
      description: '添加交通卡',
    },
    {
      path: '/add/membership',
      component: 'AddMembershipCardPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.addMembership.base', search: {}, description: '添加会员卡' }],
      queryParams: {},
      description: '添加会员卡',
    },
    {
      path: '/add/coupon',
      component: 'AddCouponPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.addCoupon.base', search: {}, description: '添加优惠券' }],
      queryParams: {},
      description: '添加优惠券',
    },
    {
      path: '/sort',
      component: 'SortCardsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.sort.base', search: {}, description: '卡片排序' }],
      queryParams: {},
      description: '卡片排序',
    },
    {
      path: '/coupons',
      component: 'CouponsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'wallet.coupons.base',
          search: {},
          description: '优惠券列表',
        },
      ],
      queryParams: {},
      description: '优惠券列表',
    },
    {
      path: '/tickets',
      component: 'TicketsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'wallet.tickets.base',
          search: {},
          description: '过期票券列表',
        },
      ],
      queryParams: {},
      description: '过期票券列表',
    },
    {
      path: '/archived',
      component: 'ArchivedTicketsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.archived.base', search: {}, description: '已归档票券' }],
      queryParams: {},
      description: '已归档票券',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.me.base', search: {}, description: '我的' }],
      queryParams: {},
      description: '我的',
    },
    {
      path: '/settings',
      component: 'SettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.settings.base', search: {}, description: '设置页' }],
      queryParams: {},
      description: '设置页',
    },
  ],
  transitions: [
    // Home
    {
      id: 'card.detail.open',
      from: ['/'],
      to: '/card/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开卡片详情',
      ui: { placement: 'content', icon: 'card', gesture: 'tap' },
    },
    {
      id: 'card.code.open',
      from: '/card/:id',
      to: '/card/:id/code',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开展示付款码',
      ui: { placement: 'content', icon: 'qrcode', gesture: 'tap' },
    },
    {
      id: 'add.bank.open',
      from: ['/'],
      to: '/add/bank',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开添加银行卡',
      ui: { placement: 'topbar', icon: 'add', gesture: 'tap' },
    },
    {
      id: 'add.transit.open',
      from: ['/'],
      to: '/add/transit',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开添加交通卡',
      ui: { placement: 'content', icon: 'add', gesture: 'tap' },
    },
    {
      id: 'add.membership.open',
      from: ['/'],
      to: '/add/membership',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开添加会员卡',
      ui: { placement: 'content', icon: 'add', gesture: 'tap' },
    },
    {
      id: 'add.coupon.open',
      from: ['/', '/coupons'],
      to: '/add/coupon',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开添加优惠券',
      ui: { placement: 'topbar', icon: 'add', gesture: 'tap' },
    },
    {
      id: 'sort.open',
      from: ['/'],
      to: '/sort',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开卡片排序',
      ui: { placement: 'content', icon: 'sort', gesture: 'tap' },
    },
    {
      id: 'coupons.open',
      from: ['/'],
      to: '/coupons',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开优惠券列表',
      ui: { placement: 'tabbar', icon: 'coupon', gesture: 'tap' },
    },
    {
      id: 'tickets.open',
      from: ['/', '/me'],
      to: '/tickets',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开过期票券列表',
      ui: { placement: 'content', icon: 'ticket', gesture: 'tap' },
    },
    {
      id: 'archived.open',
      from: '/tickets',
      to: '/archived',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开已归档票券',
      ui: { placement: 'content', icon: 'archive', gesture: 'tap' },
    },
    {
      id: 'me.open',
      from: ['/'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开我的',
      ui: { placement: 'tabbar', icon: 'me', gesture: 'tap' },
    },
    {
      id: 'settings.open',
      from: '/me',
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开设置',
      ui: { placement: 'content', icon: 'settings', gesture: 'tap' },
    },
    // Tab switching
    {
      id: 'tab.home',
      from: ['/', '/coupons', '/me'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '返回首页',
      ui: { placement: 'tabbar', icon: 'wallet', gesture: 'tap' },
    },
    {
      id: 'tab.coupons',
      from: ['/', '/me'],
      to: '/coupons',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到优惠',
      ui: { placement: 'tabbar', icon: 'coupon', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: ['/', '/coupons'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我的',
      ui: { placement: 'tabbar', icon: 'me', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
